# This is a basic workflow to help you get started with Actions

name: CI test

# Controls when the action will run. 
on:

  # Triggers the workflow on pull request events but only for the main & dev branch
  pull_request:
    branches: [ main , dev ]
  
  # Triggers the workflow on push events
  push:
    branches: [ main , dev, ci_test ]

  # Allows you to run this workflow Actions manually
  workflow_dispatch:

   # Triggers the action 2am every day
  schedule:
    - cron: "0 2 * * *"


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  ACT-sail-spike:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Install Dependencies
        run: |
          sudo xargs apt-get install -y < .github/ci-test/apt-packages.txt
          pip3 install git+https://github.com/riscv/riscof.git
          wget -c https://github.com/riscv-collab/riscv-gnu-toolchain/releases/download/2024.04.12/riscv64-elf-ubuntu-22.04-gcc-nightly-2024.04.12-nightly.tar.gz
          tar -xzf riscv64-elf-ubuntu-22.04-gcc-nightly-2024.04.12-nightly.tar.gz
          echo $GITHUB_WORKSPACE/riscv/bin >> $GITHUB_PATH

      - name: Build Spike
        run: |
          .github/ci-test/build-spike.sh
          echo $GITHUB_WORKSPACE/install/bin >> $GITHUB_PATH
      
      - name: Build sail-riscv
        run: |
          .github/ci-test/build-spike.sh
          echo $GITHUB_WORKSPACE/c_emulator >> $GITHUB_PATH
      
      - name: Test Dependencies
        run: |
          echo "testing gcc"
          riscv64-unknown-elf-gcc --version
          echo "testing riscof"
          riscof --help
          echo "testing spike"
          spike --help
          echo "testing sail-riscv"
          riscv_sim_RV32 -h
          riscv_sim_RV64 -h

